### ISSUE TITLE
`pip install shapelib` not working

### ISSUE THREAD

**Issue by laszukdawid** [gesellkammer/shapelib#3]
It seems that although `pip` and `pypi` know about `shapelib` one cannot install it. Logs below.

Resource: https://stackoverflow.com/questions/9559716/pip-finds-package-with-search-but-wont-install-it

```bash
dawid@junkyard:~/$ pip search shapelib
pyshapelib (0.0.1)  - Python bindings for shapelib and extent to
                      process shp/dbf
shapelib (0.1.0)    - Python utilities to facilitate working with
                      shapely (shape creation, rasterization,
                      plotting)
dawid@junkyard:~/$ pip install shapelib
Collecting shapelib
  Could not find a version that satisfies the requirement shapelib (from versions: )
No matching distribution found for shapelib
dawid@junkyard:~/$ pip install shapelib -vvv
Collecting shapelib
  1 location(s) to search for versions of shapelib:
  * https://pypi.python.org/simple/shapelib/
  Getting page https://pypi.python.org/simple/shapelib/
  Looking up "https://pypi.python.org/simple/shapelib/" in the cache
  Current age based on date: 375
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 375
  Analyzing links from page https://pypi.python.org/simple/shapelib/
  Could not find a version that satisfies the requirement shapelib (from versions: )
Cleaning up...
No matching distribution found for shapelib
Exception information:
Traceback (most recent call last):
...
...
...
  File "/home/dawid/.local/lib/python2.7/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for shapelib
```

**Comment by gesellkammer** [comment]
Have you tried cloning from git and doing

pip install -r requirements.txt
pip install .

It goes without saying that you should have shapely and its C requirements 
installed.

**Comment by laszukdawid** [comment]
I didn't have problem installing it through other options. Just thought that you might want to know that `pip install shapelib` doesn't work. Unless this is intended behaviour then my bad.

**Comment by gesellkammer** [comment]
That error seems to happen when mixing both pip and easy_install. Does not 
seem to be shapelib's error. See: 
https://stackoverflow.com/questions/6200056/pip-broke-how-to-fix-distributionnotfound-error

But thanks anyway for reporting

**Comment by laszukdawid** [comment]
I'm not sure whether you want any feedback on this.

Your Stackoverflow link refers to a different problem. It refers to a broken _pip_, i.e. `DistributionNotFound`for `pip` while installing anything.
The issue I've reported refers specifically to `shapelib` and that `pip` cannot find any downloadable package from _pypi_ which refers you this github project as a _Home Page_. As you can see from log provided above, pip tries to download files from https://pypi.python.org/simple/shapelib/ and there's nothing there. If you replace the last part with anything downloadable via `pip` you'll see some files and most likely *.whl. Please try NumPy link https://pypi.python.org/simple/numpy/. 

Forgive me if I am being too pesky here. Just stumbled on your project, thinking that it might be helpful. It's actually no use to me right now, but thought that I might report an issue I've noticed. I can see you've been on GitHub, and probably in general programming, much longer than I have so my intention is far from telling you any steps. Just as a sanity check, if you intend to keep this project on _pypi_, please try `pip install shapelib` your self on a clean environment. I found this (https://packaging.python.org/distributing/) to be helpful and short on maintaining _pypi_.
